# Generated by Django 5.2.12 on 2026-04-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttrDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=100, verbose_name='属性名称')),
                ('value_type', models.CharField(choices=[('str', '文本'), ('int', '整数'), ('float', '小数'), ('bool', '布尔')], default='str', max_length=10, verbose_name='属性值类型')),
                ('is_required', models.BooleanField(default=False, verbose_name='是否必填')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_defs', to='category.category', verbose_name='所属品类')),
            ],
            options={
                'verbose_name': '品类属性定义',
                'verbose_name_plural': '品类属性定义',
                'db_table': 'category_attr_def',
                'ordering': ['id'],
                'unique_together': {('category', 'attr_name')},
            },
        ),
    ]
