# Generated by Django 5.2.12 on 2026-04-20 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='商品价格')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='商品图片')),
                ('product_stock', models.IntegerField(default=0, verbose_name='库存数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='category.category', verbose_name='所属品类')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'product',
                'ordering': ['-create_time'],
            },
        ),
    ]
