# Generated by Django 5.2.12 on 2026-04-20 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_attr_def', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.CharField(blank=True, max_length=500, null=True, verbose_name='文本值')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='整数值')),
                ('value_float', models.FloatField(blank=True, null=True, verbose_name='小数值')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('attr_def', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='category_attr_def.categoryattrdef', verbose_name='属性定义')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='product.product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '商品属性值',
                'verbose_name_plural': '商品属性值',
                'db_table': 'product_attr_value',
                'ordering': ['id'],
                'unique_together': {('product', 'attr_def')},
            },
        ),
    ]
